name: Unit tests

on:
  pull_request:
    paths:
      - '*/src/**'

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt install libncurses5

      - name: Checkout project
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Run unit tests
        run: ./gradlew clean testReleaseUnitTest --no-daemon --stacktrace